# Generated by Django 3.2.23 on 2024-02-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
        migrations.AddField(
            model_name='post',
            name='mp3',
            field=models.FileField(blank=True, upload_to='mp3/'),
        ),
    ]
