# Generated by Django 3.2.23 on 2024-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_alter_beat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='mp3',
            field=models.FileField(blank=True, null=True, upload_to='mp3/'),
        ),
    ]
