# Generated by Django 3.2.23 on 2024-04-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_alter_beat_mp3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_rgq6aq', max_length=300, null=True, upload_to='images/'),
        ),
    ]
