# Generated by Django 3.2.23 on 2024-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0007_remove_beat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beat',
            name='mp3',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='mp3/'),
        ),
    ]
