# Generated by Django 3.2.23 on 2024-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dkvsdbtto/image/upload/v1712920165/media/default_profile_qdjgyp.jpg', upload_to='images/'),
        ),
    ]
