# Generated by Django 3.2.23 on 2024-02-25 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={},
        ),
        migrations.RemoveField(
            model_name='form',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='form',
            name='category',
            field=models.CharField(choices=[('fire', 'Fire'), ('cold', 'Cold'), ('banger', 'Banger'), ('snooze', 'Snooze')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
