# Generated by Django 3.2.23 on 2024-02-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20240225_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='FormSubmission',
        ),
    ]
