# Generated by Django 3.2.23 on 2024-03-05 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire', models.BooleanField(default=False)),
                ('cold', models.BooleanField(default=False)),
                ('hard', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=False)),
                ('loop', models.BooleanField(default=False)),
                ('beat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beats.beat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
