# Generated by Django 3.2.23 on 2024-03-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20240321_1155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackfire',
            unique_together=set(),
        ),
    ]
