# Generated by Django 3.2.23 on 2024-03-25 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats', '0002_alter_beat_image'),
        ('feedback', '0005_alter_feedbackfire_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackfire',
            unique_together={('owner', 'beat')},
        ),
    ]
