# Generated by Django 3.2.23 on 2024-01-25 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mp3', '0004_alter_mp3_mp3'),
        ('posts', '0001_initial'),
        ('rating', '0002_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='mp3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='mp3.mp3'),
        ),
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.post'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('owner', 'post', 'mp3')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated_at',
        ),
    ]
