# Generated by Django 3.2.23 on 2024-01-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_rating_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='mp3',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated_at',
        ),
    ]
