# Generated by Django 3.2.23 on 2024-02-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='beat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='beats.beat'),
            preserve_default=False,
        ),
    ]
