# Generated by Django 3.2.23 on 2024-02-11 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20240207_1709'),
        ('mp3', '0004_alter_mp3_mp3'),
        ('likes', '0002_auto_20240116_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='beat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='beats.beat'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'post', 'mp3', 'beat')},
        ),
    ]
