# Generated by Django 3.2.23 on 2024-01-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mp3',
            old_name='mp3_file',
            new_name='mp3',
        ),
    ]
