# Generated by Django 3.2.23 on 2024-01-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0002_rename_mp3_file_mp3_mp3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp3',
            name='mp3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
