# Generated by Django 3.2.23 on 2024-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0003_alter_mp3_mp3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp3',
            name='mp3',
            field=models.FileField(blank=True, upload_to='mp3/'),
        ),
    ]
